version: "3.8"
services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: bash -c "python scripts/init_db.py && flask run --host=0.0.0.0 --reload"
  frontend:
    build: ./campaign-manager-frontend
    volumes:
      # Only mount the source directory
      - ./campaign-manager-frontend/src:/app/src
      # Mount configuration files
      - ./campaign-manager-frontend/vite.config.js:/app/vite.config.js
      - ./campaign-manager-frontend/tailwind.config.js:/app/tailwind.config.js
      - ./campaign-manager-frontend/postcss.config.js:/app/postcss.config.js
      - ./campaign-manager-frontend/index.html:/app/index.html
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=false
      - NODE_PATH=/app/node_modules
    command: npm run dev -- --host
